DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
( EMPLOYEE_ID NUMBER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR2(250),
  LAST_NAME VARCHAR2(250),
  EMAIL VARCHAR2(250),
  BUSINESS_UNIT VARCHAR2(250),
  CITY VARCHAR2(250),
  COUNTRY VARCHAR2(250),
  DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DATE_LAST_MODIFIED TIMESTAMP,
  MODIFICATION_COUNT NUMBER DEFAULT 0
);